### ISSUE TITLE
`x-order` require value of `number` to be in quotes

### ISSUE THREAD

**Issue by ChandanChainani** [go-openapi/spec#162]
```
type User struct {
  // User name
  // Extensions:
  // x-order: 0
  Username string json:"username"
  // Password
  // Extensions:
  // x-order: 1
  Password string json:"password"
}

// userInfo request payload
// swagger:response userInfo
type swaggUserInfo struct {
  // in:body
  Body User
}
```
Output without quotes:
```
userInfo:
  properties:
    password:
      type: string
      x-go-name: Password
      x-order: 1
    username:
      type: string
      x-go-name: Username
      x-order: 0
```

```
type User struct {
  // User name
  // Extensions:
  // x-order: "0"
  Username string json:"username"
  // Password
  // Extensions:
  // x-order: "1"
  Password string json:"password"
}

// userInfo request payload
// swagger:response userInfo
type swaggUserInfo struct {
  // in:body
  Body User
}
```
Output with quotes:
```
userInfo:
  properties:
    username:
      type: string
      x-go-name: Username
      x-order: 0
    password:
      type: string
      x-go-name: Password
      x-order: 1
```
