### ISSUE TITLE
When the maximum type is float64, using json.Unmarshal(raw, &spec.Swagger{}) will lose precision

### ISSUE THREAD

**Issue by O3cheng** [go-openapi/spec#201]
When the maximum type is float64, using json.Unmarshal(raw, &spec.Swagger{}) will lose precision

```yaml
definitions:
  TestResponse:
    description: test
    type: object
    properties:
      test_1:
        description: test_1
        type: long
        format: int64
        **maximum: 9223372036854775807**
        minimum: 0
```

because
```go
type SchemaProps struct {
	Maximum              *float64         `json:"maximum,omitempty"`
}
```
